rootProject.name = 'library'
include ':entrypoints'
include ':postgres'
include ':models'
include ':uses-cases'
include ':email'
include ':images'


project(':entrypoints')?.projectDir = file('./infrastructure/entrypoints')
project(':postgres')?.projectDir = file('./infrastructure/driven-adapters/postgres')
project(':models')?.projectDir = file('./domain/models')
project(':uses-cases')?.projectDir = file('./applications/uses-cases')
project(':email')?.projectDir = file('./infrastructure/driven-adapters/email')
project(':images')?.projectDir = file('./infrastructure/driven-adapters/images')

