plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.4'
}

dependencies {
    implementation project(':models')
    implementation project(':postgres')
    implementation project(':uses-cases')

    implementation "org.springframework.boot:spring-boot-starter-web:${springVersion}"
    testImplementation "org.springframework.boot:spring-boot-starter-test:${springVersion}"
    implementation "org.springframework.boot:spring-boot-starter-data-jpa:${springVersion}"
    implementation group: 'org.springframework.boot', name: 'spring-boot-starter-validation', version: '3.3.4'
    implementation group: 'org.hibernate', name: 'hibernate-entitymanager', version: '5.2.10.Final'
    implementation group: 'jakarta.validation', name: 'jakarta.validation-api', version: '3.1.0'
    implementation group: 'org.springdoc', name: 'springdoc-openapi-starter-webmvc-ui', version: '2.6.0'

}
