plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.4'
}

dependencies {
    implementation project(':models')
    implementation project(':postgres')
    implementation project(':uses-cases')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    implementation group: 'jakarta.validation', name: 'jakarta.validation-api', version: '3.1.0'
    implementation group: 'org.springdoc', name: 'springdoc-openapi-starter-webmvc-ui', version: '2.6.0'

}
